xpos314/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly CategoryTryService categoryTryService;

        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryService = new CategoryTryService(db);
        }

        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryService.GetAllData();
            return View(dataView);
        }

        public IActionResult Create() 
        {
            VMTblCategory viewModel = new VMTblCategory();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if(ModelState.IsValid)
            {
                respon = categoryTryService.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if(ModelState.IsValid)
            {
                respon = categoryTryService.Edit(dataView);
                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

 
        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {

            /*Menghapus menggunakan validasi*/
            /*VMResponse respon = new VMResponse();
            //Menghapus kolom yang required saat model divalidasi//
            ModelState.Remove("NameCategory");
            if (ModelState.IsValid)
            {
                respon = categoryTryService.Delete(dataView);
                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }*/

            VMResponse respon = categoryTryService.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }
    }
}

xpos314/xpos314.web/Views/CategoryTry/Create.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
     ViewData["Title"] = "Create Category";
     Layout=null;
}
<div class="card mt-4">
    <div class="card-body">
    <h4 class="card-title">@ViewData["Title"]</h4>
  <form asp-action="Create" method="POST">
  <div class="form-group row mb-2">
    <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory">
      <span class="text-danger" asp-validation-for="NameCategory"></span>
    </div>
  </div>
  <div class="form-group row mb-2">
    <label for="Description" class="col-sm-4 col-form-label">Description</label>
    <div class="col-sm-8">
      <input type="text" class="form-control" name="Description" id="Description">
    </div>
  </div>
  &nbsp;
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
       <a class="btn btn-secondary" asp-controller="CategoryTry" asp-action="Index">Back</a>
    </div>
  </div>
</form>
</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
      ViewData["Title"] = "Delete Category";
}

<div class="card">
    <div class="card-body">
        <form asp-action="Delete" method="POST">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"></input>

            <h3>Are you sure for delete @Model.NameCategory ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            <div>
        </form>
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Detail.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
      Layout=null;
      ViewData["Title"] = "Detail Category";
}
<div class="card">
    <div class="card-header d-lg-flex">
        <h3 class="card-title font-weight-bold mr-2 mt-2">@ViewData["Title"]</h3>  
    </div>
    <div class="card-body">
  <div class="form-group row mb-2">
    <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory" readonly>
      <span class="text-danger" asp-validation-for="NameCategory"></span>
    </div>
  </div>
  <div class="form-group row mb-2">
    <label for="Description" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="Description" id="Description" value="@Model.Description" readonly>
    </div>
  </div>
</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Edit.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
      ViewData["Title"] = "Edit Category";
      Layout=null;
}
<div class="card">
    <div class="card-body">
    <h4 mb-2>@ViewData["Title"]</h4>
  <form asp-action="Edit" method="POST">
   <input type="hidden" id="Id" name="Id" value="@Model.Id"></input>
  <div class="form-group row mb-2">
    <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory">
      <span class="text-danger" asp-validation-for="NameCategory"></span>
    </div>
  </div>
  <div class="form-group row mb-2">
    <label for="Description" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="Description" id="Description" value="@Model.Description">
    </div>
  </div>
  &nbsp;
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
       <a class="btn btn-secondary" asp-controller="CategoryTry" asp-action="Index">Back</a>
    </div>
  </div>
</form>
</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Index.cshtml
@using xpos314.viewmodels
@{
    ViewData["Title"] = "Category Try";
}

<div class="card">
    <div class="card-body">
        <h1 class="card-title mb-4">@ViewData["Title"]</h1>
        @*<div class="row mb-2">
            <div class="col-12 d-flex justify-content-between">
            <form asp-action="Index" method="GET" id="form_search">
                <div class="customize-input float-right">
                    <div class="input-group">
                        <input type="text" class="form-control" name="searchString" value="@ViewBag.currentFilter" placeholder="Search.."/>
                        <div class="input-group-prepend"> 
                                <button type="submit" class="btn btn-secondary" id="btn_search"><i data-feather="search"></i></button>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        </div>*@
        <a class="btn btn-primary mr-2 mb-2 btn-rounded" style="color: white" id="btn_add"><i data-feather="plus"></i></a>
        <table class="table table-hover table-striped ">
          <thead>
            <tr>
              <th scope="col">Id</th>
              <th scope="col">Name Category</th>
              <th scope="col">Description</th>
              <th scope="col" class="text-center align-middle">Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach(VMTblCategory item in Model)
            {
            <tr>
              <th scope="row">@item.Id</th>
              <td>@item.NameCategory</td>
              <td>@item.Description</td>
              <td class="text-center align-middle"><a class="btn btn-primary btn-rounded btn_edit" style="color: white" data-id="@item.Id"><i data-feather="edit"></i></a> &nbsp;
                  <a class="btn btn-success btn-rounded btn_detail" style="color: white" data-id="@item.Id"> <i data-feather="user-check"></i></a> &nbsp;
                  <a class="btn btn-danger btn-rounded btn_delete" style="color: white" data-id="@item.Id"> <i data-feather="trash"></i></a>
              </td>
            </tr>
            }
          </tbody>
        </table>
</div>
</div>

<script>
    $(document).ready(function(){
        $("#btn_add").click(function(){
            $(".body-modal").load("/CategoryTry/Create");
            $("#myModal").modal("show");
            //alert("masuk");
        });

        $(".btn_edit").click(function(){
            var id = $(this).data("id")
            $(".body-modal").empty()
            $(".body-modal").load("/CategoryTry/Edit?id=" + id);
            $("#myModal").modal("show");
        });

        $(".btn_detail").click(function(){
            var id = $(this).data("id")
            $(".body-modal").empty()
            $(".body-modal").load("/CategoryTry/Detail?id=" + id);
            $("#myModal").modal("show");
        });

        $(".btn_delete").click(function(){
            var id = $(this).data("id")
            $(".body-modal").empty()
            $(".body-modal").load("/CategoryTry/Delete?id=" + id);
            $("#myModal").modal("show");
        });
    });
</script>